package team.a9043.privacy_assessment_system.pojo;

public class WbData {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wb_data.data_ID
     *
     * @mbg.generated
     */
    private Integer dataId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wb_data.uid
     *
     * @mbg.generated
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wb_data.create_time
     *
     * @mbg.generated
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wb_data.weibo_cont
     *
     * @mbg.generated
     */
    private String weiboCont;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wb_data.data_ID
     *
     * @return the value of wb_data.data_ID
     *
     * @mbg.generated
     */
    public Integer getDataId() {
        return dataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wb_data.data_ID
     *
     * @param dataId the value for wb_data.data_ID
     *
     * @mbg.generated
     */
    public void setDataId(Integer dataId) {
        this.dataId = dataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wb_data.uid
     *
     * @return the value of wb_data.uid
     *
     * @mbg.generated
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wb_data.uid
     *
     * @param uid the value for wb_data.uid
     *
     * @mbg.generated
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wb_data.create_time
     *
     * @return the value of wb_data.create_time
     *
     * @mbg.generated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wb_data.create_time
     *
     * @param createTime the value for wb_data.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wb_data.weibo_cont
     *
     * @return the value of wb_data.weibo_cont
     *
     * @mbg.generated
     */
    public String getWeiboCont() {
        return weiboCont;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wb_data.weibo_cont
     *
     * @param weiboCont the value for wb_data.weibo_cont
     *
     * @mbg.generated
     */
    public void setWeiboCont(String weiboCont) {
        this.weiboCont = weiboCont == null ? null : weiboCont.trim();
    }
}