package team.a9043.privacy_assessment_system.pojo;

public class WbData {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wb_data.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wb_data.uid
     *
     * @mbg.generated
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wb_data.create_time
     *
     * @mbg.generated
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wb_data.wb_cont
     *
     * @mbg.generated
     */
    private String wbCont;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wb_data.id
     *
     * @return the value of wb_data.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wb_data.id
     *
     * @param id the value for wb_data.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wb_data.uid
     *
     * @return the value of wb_data.uid
     *
     * @mbg.generated
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wb_data.uid
     *
     * @param uid the value for wb_data.uid
     *
     * @mbg.generated
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wb_data.create_time
     *
     * @return the value of wb_data.create_time
     *
     * @mbg.generated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wb_data.create_time
     *
     * @param createTime the value for wb_data.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wb_data.wb_cont
     *
     * @return the value of wb_data.wb_cont
     *
     * @mbg.generated
     */
    public String getWbCont() {
        return wbCont;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wb_data.wb_cont
     *
     * @param wbCont the value for wb_data.wb_cont
     *
     * @mbg.generated
     */
    public void setWbCont(String wbCont) {
        this.wbCont = wbCont == null ? null : wbCont.trim();
    }
}