package team.a9043.privacy_assessment_system.pojo;

public class WbUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wb_user.user_ID
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wb_user.uid
     *
     * @mbg.generated
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wb_user.Uname
     *
     * @mbg.generated
     */
    private String uname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wb_user.Certified
     *
     * @mbg.generated
     */
    private String certified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wb_user.Sex
     *
     * @mbg.generated
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wb_user.Relationship
     *
     * @mbg.generated
     */
    private String relationship;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wb_user.Area
     *
     * @mbg.generated
     */
    private String area;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wb_user.Birthday
     *
     * @mbg.generated
     */
    private String birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wb_user.Education_info
     *
     * @mbg.generated
     */
    private String educationInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wb_user.Work_info
     *
     * @mbg.generated
     */
    private String workInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wb_user.Description
     *
     * @mbg.generated
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wb_user.user_ID
     *
     * @return the value of wb_user.user_ID
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wb_user.user_ID
     *
     * @param userId the value for wb_user.user_ID
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wb_user.uid
     *
     * @return the value of wb_user.uid
     *
     * @mbg.generated
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wb_user.uid
     *
     * @param uid the value for wb_user.uid
     *
     * @mbg.generated
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wb_user.Uname
     *
     * @return the value of wb_user.Uname
     *
     * @mbg.generated
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wb_user.Uname
     *
     * @param uname the value for wb_user.Uname
     *
     * @mbg.generated
     */
    public void setUname(String uname) {
        this.uname = uname == null ? null : uname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wb_user.Certified
     *
     * @return the value of wb_user.Certified
     *
     * @mbg.generated
     */
    public String getCertified() {
        return certified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wb_user.Certified
     *
     * @param certified the value for wb_user.Certified
     *
     * @mbg.generated
     */
    public void setCertified(String certified) {
        this.certified = certified == null ? null : certified.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wb_user.Sex
     *
     * @return the value of wb_user.Sex
     *
     * @mbg.generated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wb_user.Sex
     *
     * @param sex the value for wb_user.Sex
     *
     * @mbg.generated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wb_user.Relationship
     *
     * @return the value of wb_user.Relationship
     *
     * @mbg.generated
     */
    public String getRelationship() {
        return relationship;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wb_user.Relationship
     *
     * @param relationship the value for wb_user.Relationship
     *
     * @mbg.generated
     */
    public void setRelationship(String relationship) {
        this.relationship = relationship == null ? null : relationship.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wb_user.Area
     *
     * @return the value of wb_user.Area
     *
     * @mbg.generated
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wb_user.Area
     *
     * @param area the value for wb_user.Area
     *
     * @mbg.generated
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wb_user.Birthday
     *
     * @return the value of wb_user.Birthday
     *
     * @mbg.generated
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wb_user.Birthday
     *
     * @param birthday the value for wb_user.Birthday
     *
     * @mbg.generated
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday == null ? null : birthday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wb_user.Education_info
     *
     * @return the value of wb_user.Education_info
     *
     * @mbg.generated
     */
    public String getEducationInfo() {
        return educationInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wb_user.Education_info
     *
     * @param educationInfo the value for wb_user.Education_info
     *
     * @mbg.generated
     */
    public void setEducationInfo(String educationInfo) {
        this.educationInfo = educationInfo == null ? null : educationInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wb_user.Work_info
     *
     * @return the value of wb_user.Work_info
     *
     * @mbg.generated
     */
    public String getWorkInfo() {
        return workInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wb_user.Work_info
     *
     * @param workInfo the value for wb_user.Work_info
     *
     * @mbg.generated
     */
    public void setWorkInfo(String workInfo) {
        this.workInfo = workInfo == null ? null : workInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wb_user.Description
     *
     * @return the value of wb_user.Description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wb_user.Description
     *
     * @param description the value for wb_user.Description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}