package team.a9043.privacy_assessment_system.pojo;

import java.util.Date;

public class WbUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wb_user.uid
     *
     * @mbg.generated
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wb_user.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wb_user.certified
     *
     * @mbg.generated
     */
    private String certified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wb_user.sex
     *
     * @mbg.generated
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wb_user.relationship
     *
     * @mbg.generated
     */
    private String relationship;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wb_user.area
     *
     * @mbg.generated
     */
    private String area;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wb_user.birthday
     *
     * @mbg.generated
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wb_user.education_info
     *
     * @mbg.generated
     */
    private String educationInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wb_user.work_info
     *
     * @mbg.generated
     */
    private String workInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wb_user.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wb_user.uid
     *
     * @return the value of wb_user.uid
     *
     * @mbg.generated
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wb_user.uid
     *
     * @param uid the value for wb_user.uid
     *
     * @mbg.generated
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wb_user.name
     *
     * @return the value of wb_user.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wb_user.name
     *
     * @param name the value for wb_user.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wb_user.certified
     *
     * @return the value of wb_user.certified
     *
     * @mbg.generated
     */
    public String getCertified() {
        return certified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wb_user.certified
     *
     * @param certified the value for wb_user.certified
     *
     * @mbg.generated
     */
    public void setCertified(String certified) {
        this.certified = certified == null ? null : certified.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wb_user.sex
     *
     * @return the value of wb_user.sex
     *
     * @mbg.generated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wb_user.sex
     *
     * @param sex the value for wb_user.sex
     *
     * @mbg.generated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wb_user.relationship
     *
     * @return the value of wb_user.relationship
     *
     * @mbg.generated
     */
    public String getRelationship() {
        return relationship;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wb_user.relationship
     *
     * @param relationship the value for wb_user.relationship
     *
     * @mbg.generated
     */
    public void setRelationship(String relationship) {
        this.relationship = relationship == null ? null : relationship.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wb_user.area
     *
     * @return the value of wb_user.area
     *
     * @mbg.generated
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wb_user.area
     *
     * @param area the value for wb_user.area
     *
     * @mbg.generated
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wb_user.birthday
     *
     * @return the value of wb_user.birthday
     *
     * @mbg.generated
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wb_user.birthday
     *
     * @param birthday the value for wb_user.birthday
     *
     * @mbg.generated
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wb_user.education_info
     *
     * @return the value of wb_user.education_info
     *
     * @mbg.generated
     */
    public String getEducationInfo() {
        return educationInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wb_user.education_info
     *
     * @param educationInfo the value for wb_user.education_info
     *
     * @mbg.generated
     */
    public void setEducationInfo(String educationInfo) {
        this.educationInfo = educationInfo == null ? null : educationInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wb_user.work_info
     *
     * @return the value of wb_user.work_info
     *
     * @mbg.generated
     */
    public String getWorkInfo() {
        return workInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wb_user.work_info
     *
     * @param workInfo the value for wb_user.work_info
     *
     * @mbg.generated
     */
    public void setWorkInfo(String workInfo) {
        this.workInfo = workInfo == null ? null : workInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wb_user.description
     *
     * @return the value of wb_user.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wb_user.description
     *
     * @param description the value for wb_user.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}