package team.a9043.privacy_assessment_system.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import team.a9043.privacy_assessment_system.pojo.WbData;
import team.a9043.privacy_assessment_system.pojo.WbDataExample;

public interface WbDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wb_data
     *
     * @mbg.generated
     */
    long countByExample(WbDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wb_data
     *
     * @mbg.generated
     */
    int deleteByExample(WbDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wb_data
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer dataId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wb_data
     *
     * @mbg.generated
     */
    int insert(WbData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wb_data
     *
     * @mbg.generated
     */
    int insertSelective(WbData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wb_data
     *
     * @mbg.generated
     */
    List<WbData> selectByExampleWithBLOBs(WbDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wb_data
     *
     * @mbg.generated
     */
    List<WbData> selectByExample(WbDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wb_data
     *
     * @mbg.generated
     */
    WbData selectByPrimaryKey(Integer dataId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wb_data
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") WbData record, @Param("example") WbDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wb_data
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") WbData record, @Param("example") WbDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wb_data
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") WbData record, @Param("example") WbDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wb_data
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(WbData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wb_data
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(WbData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wb_data
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WbData record);
}