package team.a9043.privacy_assessment_system.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import team.a9043.privacy_assessment_system.pojo.WbUser;
import team.a9043.privacy_assessment_system.pojo.WbUserExample;

public interface WbUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wb_user
     *
     * @mbg.generated
     */
    long countByExample(WbUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wb_user
     *
     * @mbg.generated
     */
    int deleteByExample(WbUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wb_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wb_user
     *
     * @mbg.generated
     */
    int insert(WbUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wb_user
     *
     * @mbg.generated
     */
    int insertSelective(WbUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wb_user
     *
     * @mbg.generated
     */
    List<WbUser> selectByExample(WbUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wb_user
     *
     * @mbg.generated
     */
    WbUser selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wb_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") WbUser record, @Param("example") WbUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wb_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") WbUser record, @Param("example") WbUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wb_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(WbUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wb_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WbUser record);
}